name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload API
        uses: actions/upload-artifact@v1.0.0
        with:
          name: yggdrasil-api
          path: api/build/libs
      - name: Upload Core
        uses: actions/upload-artifact@v1.0.0
        with:
          name: yggdrasil-core
          path: core/build/libs
      - name: Move build things to artifact folder
        run: | 
          mkdir artifact 
          mv api/build/libs/*.jar artifact/ 
          mv core/build/libs/*.jar artifact/
      - name: Upload all artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: yggdrasil-all
          path: artifact
